name: Highlighter
main: me.iffa.highlighter.Highlighter
version: 0.3
depend: [Spout]
commands:
    highlighter:
        description: Adds a new highlight
        usage: /<command>
        permission: highlighter.commands